# -*- coding: utf-8 -*-
"""NS_graph

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JWVNn1RPGlhlNC0zZWqPc0R4hA8UplWf

## Set up
"""

# Commented out IPython magic to ensure Python compatibility.
## imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.plotting.register_matplotlib_converters()
# %matplotlib inline
import seaborn as sns
print("Setup Complete")

provinces = np.array(['NL', 'PE', 'NS', 'NB', 'QC', 'ON', 'MB', 'SK', 'AB', 'BC', 'YT', 'NT', 'NU'])
print(provinces)
# print(provinces[3])
# print(type(provinces))

# for item in provinces:
#  if item == a:
#    print("Yes")
#  else: 
#    print("Invalid input")
#    break;

"""NL Data"""

## checking the files
import os
from google.colab import files
NS_water = files.upload()
print("File Uploaded")

import io
df_NS = pd.read_csv(io.BytesIO(NS_water['NS_waterlevels.csv']))
print("Dataset is now stored in a Pandas Dataframe")

# make sure data is clean

# first 5 rows
df_NS.head()

# last 5 rows
df_NS.tail()

"""Plot the Data - NS




"""

# Line chart showing water levels in a certain province 
# sns.lineplot(data=df_NL)

# Set the width and height of the figure
plt.figure(figsize=(14,6))

# for every day
arr = np.array([24, 48, 72, 96, 120, 144, 168, 192, 216, 240, 264, 288, 312, 336, 
                360, 384, 408, 432, 456, 480, 504, 528, 552, 576, 600, 624, 648, 
                672, 696, 720])

for a in range(30):
  var = arr[a];
  plt.axvline(x = var, color ='lightblue', linewidth = 0.5)

plt.axhline(y=0.559, color="#4682B4", linewidth = 0.6)

# Add title
plt.title("Water Levels and Recommended Level for Nova Scotia for the past 30 days from today", color = 'blue')

# x label
plt.xlabel("Data for the past 30 days from today (blue lines indicating a different day and x values indicating hourly values)")

# y label
plt.ylabel("Water level (in m)")

# limits
plt.ylim(top = 0.575)
plt.ylim(bottom = 0.461)

# Line chart 
sns.lineplot(data=df_NS)

